### ISSUE TITLE
Student waiting list / Duplicate volunteers bug

### ISSUE THREAD

**Issue by lualparedes** [UPchieve/web#134] opened 2018-12-12 22:23 UTC
Ideally, the list of students waiting for help should update as soon as a volunteer joins the session started by the student. No new volunteers should be able to enter a session if there's already a volunteer in it.

We need to:
- Review the logic that handles how the list of waiting students updates, to make sure that it's working correctly
- Add some extra logic to 
  - block a session for any other volunteer as soon as the first volunteer joins
  - display a "thank you for your interest, but another volunteer is already helping the student" message

The extra logic may seem optional but it's ideal both for the sake of graceful rejection and for the sake of software robustness.

**Comment by alymurray** [comment] 2019-01-31 17:06
Most recently, I had a session where myself and another volunteer selected a student at the same time. We were both in the sesion and could see each other's messages and the student's messages, but the student could not see ours or what we wrote on the whiteboard. We both left the session and saw that the student was still showing up in the list of students waiting for help. I freshly selected th estudent, and they were removed from the waiting list, but it appeared that the student still couldn't see the messages I was sending or what I was writing on the whiteboard.

**Comment by alymurray** [comment] 2019-01-31 17:07
![image](https://user-images.githubusercontent.com/20755642/52071314-b3765980-2550-11e9-8322-64416ce0ac0c.png)


![image](https://user-images.githubusercontent.com/20755642/52071264-99d51200-2550-11e9-85ad-7dd9b884abbd.png)
(From most recent attempt to select the student)

**Comment by lualparedes** [comment] 2019-03-05 04:03
Backend solution: https://github.com/UPchieve/server/pull/71

**Comment by jmromer** [comment] 2019-03-06 20:15
The root cause for this bug is addressed by https://github.com/UPchieve/server/pull/73 but we can still iterate on UPchieve/server#71 to eliminate a race condition there.

**Closed** 2019-03-07 01:39 UTC
Labels: bug, enhancement
